l_english:

 ### Settings Event Chain
 
 VU_SET_Events.01.t: "Victorum Universalis Settings"
 VU_SET_Events.01.d: "Welcome to Victorum Universalis!\nThis event is here to help you set up the most enjoyable experience for the mod.\n\nThe §G'Recommended Mode'§! is how I personally recommend you play if it's your first time with the mod, so you can fully experience all the new provinces, nations, cultures, religions and content the mod adds.\nBut due to all our extra content, the game might run slowly for some, so you could try §T'Performance Mode'§! and see if it helps.\n\nThere is also an event chain where you can manually select each of the options to create the experience you would enjoy!\nEach of the events will also explain how each setting works in case you are interested.\n\nWe hope you enjoy playing this mod as much as we enjoyed making it!\n- The Victorum Universalis Dev Team"
 VU_SET_Events.01.a: "Enable §GRecommended§! Mode" #All the (Recommended) options.
 VU_SET_Events.01.b: "Enable §TPerformance§! Mode" #All the (Performance) options when available, (Recommended) when not.
 VU_SET_Events.01.c: "I wish to pick each option myself"
 
 VU_SET_Events.01.b.tt: "§GThe game may freeze for a minute, but just wait and it will resume.§!"

 VU_SET_Events.02.t: "Nations of the World"
 VU_SET_Events.02.d: "What hurts performance the most in Victorum Universalis is the large number of new nations that were added for historical accuracy. However, if you choose to experience the mod without them, it will perform better."
 VU_SET_Events.02.a: "Expanded Nations §G(Recommended)§!" #Nothing happens
 VU_SET_Events.02.b: "Vanilla Nations §T(Performance)§!" #'Enable Vanilla Setup' decision

 VU_SET_Events.03.t: "Natives & Primitives"
 VU_SET_Events.03.d: "Would you like to keep or remove the primitive and native nations from the Americas, Africa and Oceania?\n\nIt's recommended to keep them to enrich those regions, but the game may run faster without them.\nAlternatively, you can leave only the most advanced among them while deleting all the primitive tribes."
 VU_SET_Events.03.a: "Keep them §G(Recommended)§!" #Nothing happens
 VU_SET_Events.03.b: "Remove them all §T(Performance)§!" #Removes ALL native and primitive nations
 VU_SET_Events.03.c: "Remove insignificant natives §T(Compromise)§!" #Removes most of primitive nations, while leaving only some like Aztecs, Mayas, Incas, etc.

 VU_SET_Events.04.t: "Historical Colonisation"
 VU_SET_Events.04.d: "Historical Colonisation will prevent AI-controlled nations from colonizing places they didn't colonize in real life. This helps prevent ahistorical colonies from constantly appearing, like Portuguese La Plata or English Mexico.\nIt won't, however, outright prevent ahistorical nations/colonies from forming - it's still possible for the AI to take provinces/colonies in a war -, it just becomes rarer than usual.\n\nRecommended if you want more historically accurate colonies, but can be too 'railroaded' for some."
 VU_SET_Events.04.a: "Enabled §G(Recommended)§!" #Nothing happens
 VU_SET_Events.04.b: "Disabled" #Disables Historical Colonisation

 VU_SET_Events.05.t: "Age Restrictions for Colonization"
 VU_SET_Events.05.d: "Age Restrictions prevents all nations (player and AI) from colonizing specific colonial nations before a certain age is reached (ex. Colonial Louisiana is 'unlocked' in the Age of Absolutism and can't be colonized before that).\n\nRecommended if you'd like to have a more historically accurate game, but can get a bit chaotic when 'Historical Colonisation' is disabled."
 VU_SET_Events.05.a: "Enabled §G(Recommended)§!" #Nothing happens
 VU_SET_Events.05.b: "Disabled" #Disables Age Restrictions

 VU_SET_Events.06.t: "Hard to Colonise"
 VU_SET_Events.06.d: "Provinces which were not colonised before the 1850s have the province modifier 'Hard to Colonise' and can't be colonised before Diplomatic Technology 35 (~1850s). If taken in a war they will be returned to the previous owner or abandoned it (if there is no previous owner).\nNative american, africans and aboriginals aren't affected by it.\n\nRecommended if you want to prevent europeans from taking large chunks of Africa in the 1500s."
 VU_SET_Events.06.a: "Enabled §G(Recommended)§!" #Nothing happens
 VU_SET_Events.06.b: "Disabled" #'Hard to Colonise' province modifier is removed from all provinces